name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: tezz-io/genREADME@main
        with:
          file: MAIN.md
          with_title: true
          n_hashes: 2
      - run: |
          git add .
          git commit -m "Generated README.md"
          git push
