name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tezz-io/genREADME@main
        with:
          file: MAIN.md
          with_title: true
          n_hashes: 2
      - name: Setup Username
        run: git config user.name tezz-io
      - name: Setup Email
        run: git config user.email totejasmr@gmail.com
      - name: Push generated README.md  
        run: |
          git add .
          git commit -m "Generated README.md"
          git push
